# Generated by Django 3.1.2 on 2020-10-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('consti_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('date_of_elections', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(blank=True, max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('a_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=25)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election_officer',
            fields=[
                ('ec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('consti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('m_status', models.CharField(max_length=1)),
                ('consti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.constituency')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.party')),
            ],
        ),
    ]
