# Generated by Django 3.1.2 on 2020-10-21 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0002_election_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='closes_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
