# Generated by Django 3.1.2 on 2020-10-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0003_election_closes_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='closes_on',
        ),
    ]
